version: "3"

services:
    celery:
        build: ../
        container_name: celery-worker
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        depends_on:
            - redis
        volumes:
            - ../myshop/db.sqlite3:/app/db.sqlite3

    redis:
        image: redis:latest
        container_name: redis-container
        ports:
            - "6379:6379"

    stripe:
        image: stripe/stripe-cli:latest
        container_name: stripe-cli
        network_mode: host # Чтобы использовать хостовую сеть
        env_file:
            - ../.env
        command: listen --forward-to localhost:8000/payment/webhook/
