# Generated by Django 5.1 on 2024-08-28 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="код купона"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        verbose_name="дата и время начала действия купона"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        verbose_name="дата и время окончания действия купона"
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        help_text="Процентное значение (от 0 до 100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="процент скидки",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="активен")),
            ],
            options={
                "verbose_name": "Купон",
                "verbose_name_plural": "Купоны",
            },
        ),
    ]
